import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Sidebar from "@/components/Sidebar";
import { ToastContainer } from "react-toastify";
export const metadata: Metadata = {
  title: "My LMS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      <ToastContainer />

        <Navbar />
        <div>
          <Sidebar />
          <main className='dashboard-parent-container'>
            {children}
          </main>
        </div>        
      </body>
    </html>
  );
}
